### PR TITLE
Corrects #19 and upgrades plugin's compatibility to Confluence 5.9.2

### PR DESCRIPTION
**Pull request by sebValiantys**
The error described by rorydavidson and  NicolasEsteves  came from a change of java apis. The fix consisted in correcting the faulty api calls. I also replaced some deprecated calls. Not all deprecated uses have been changed.

In order to build the plugin I also had to add dependencies to the pom which I haven't commited , namely: 
```xml
    <dependency>
      <groupId>org.apache.axis</groupId>
       <artifactId>axis</artifactId>
       <version>1.4</version>
    </dependency>
    <dependency>
       <groupId>javax.xml</groupId>
       <artifactId>jaxrpc-api</artifactId>
       <version>1.1.1</version>
    </dependency>
```
I can still commit these changes if needed.

Overview of the changes : 
 - Switches some calls to deprecated getRemoteUser method to use getAuthenticatedUser instead (as stated in https://docs.atlassian.com/confluence/latest/index.html?com/atlassian/confluence/plugin/webresource/ConfluenceWebResourceManager.html)
 - Switches WebResourceManager to ConfluenceWebResourceService (as stated in https://docs.atlassian.com/confluence/latest/com/atlassian/confluence/plugin/webresource/ConfluenceWebResourceManager.html)
 - Corrects call to spaceDao.getSpaces to pass mandatory SpaceQueryWithPermissionBuilder
 - Switches call to spacePermissionManager.hasPermission to spacePermission.hasAllPermissions (as stated in https://docs.atlassian.com/confluence/latest/index.html?com/atlassian/confluence/plugin/webresource/ConfluenceWebResourceManager.html)

### CODE REVIEW

**Comment by garysweaver** [comment]
@sebValiantys Awesome work!! Thanks!! Yes, could you amend the commit to add those two dependencies and also to change pom.xml to 2.4.0-SNAPSHOT vs 2.3.1-SNAPSHOT (and I apologize it should have been on a snapshot version anyway- I dropped the ball on that)?

If so, then will merge and release if all looks good.

If you don't have time, just let me know and I'll just merge later and fix those. Thanks again!!

**Comment by sebValiantys** [comment]
@garysweaver your are welcome. It's on my workstation and I am away from it until next Monday. I can do it by then.

**Comment by garysweaver** [comment]
No worries. I'll go ahead and merge and make those changes. Thanks!

**Comment by garysweaver** [comment]
Released fix in 5.4.0. Let me know if can verify it works for you.

**Comment by sebValiantys** [comment]
Good to know, will check soon.

Cheers

*Sébastien DELCOIGNE*
[image: Valiantys]
<http://www.valiantys.com?utm_source=Signature&utm_medium=referral&utm_campaign=Other%20Links>
Tél : +33 (0)5 62 24 47 62
118 Route d'Espagne, Bâtiment A, 3ème étage - 31100 TOULOUSE - FRANCE
www.valiantys.com
<http://www.valiantys.com?utm_source=Signature&utm_medium=referral&utm_campaign=Other%20Links>•
blog.valiantys.com
<http://blog.valiantys.com?utm_source=Signature&utm_medium=referral&utm_campaign=Other%20Links>
• twitter.com/Valiantys



*Consultez nos formations Atlassian
<http://www.valiantys.com/services/formation?utm_source=Signature%20Tagline&utm_medium=referral&utm_campaign=Other%20Links>
disponibles dans le monde entier et réservez vos places dès maintenant ! *Take
a look at our worldwide Atlassian training courses
<http://www.valiantys.com/en/our-services/training?utm_source=Signature%20Tagline&utm_medium=referral&utm_campaign=Other%20Links>
and book now!

<https://marketplace.atlassian.com/plugins/com.valiantys.spreadsheets>

**Comment by sebValiantys** [comment]
Hi Gary,

We've noticed an incompatibility with the new version of the plugin. We use
it along with Bob Swift's CLI plugin and with the updated version, the
second plugin crashes when Confluence restarts. I am trying to investigate
the origin of the problem and will let you know the findings.

Regards

*Sébastien DELCOIGNE*
[image: Valiantys]
<http://www.valiantys.com?utm_source=Signature&utm_medium=referral&utm_campaign=Other%20Links>
Tél : +33 (0)5 62 24 47 62
118 Route d'Espagne, Bâtiment A, 3ème étage - 31100 TOULOUSE - FRANCE
www.valiantys.com
<http://www.valiantys.com?utm_source=Signature&utm_medium=referral&utm_campaign=Other%20Links>•
blog.valiantys.com
<http://blog.valiantys.com?utm_source=Signature&utm_medium=referral&utm_campaign=Other%20Links>
• twitter.com/Valiantys



*Consultez nos formations Atlassian
<http://www.valiantys.com/services/formation?utm_source=Signature%20Tagline&utm_medium=referral&utm_campaign=Other%20Links>
disponibles dans le monde entier et réservez vos places dès maintenant ! *Take
a look at our worldwide Atlassian training courses
<http://www.valiantys.com/en/our-services/training?utm_source=Signature%20Tagline&utm_medium=referral&utm_campaign=Other%20Links>
and book now!

<https://marketplace.atlassian.com/plugins/com.valiantys.spreadsheets>

**Comment by sebValiantys** [comment]
Quick update:
We've tested with the previous version of the plugin on Confluence 5.8 +
BOB Swift's CLI : no error. We've also tried to add all plugins one at a
time and restart confluence each time and the problem arises only when CSUM
is added with the current version.
Only real difference to the plugin is this addition of the dependencies. I
am no expert on this subject, but I am testing different options to see if
the problem persists.

Cheers,

*Sébastien DELCOIGNE*
[image: Valiantys]
<http://www.valiantys.com?utm_source=Signature&utm_medium=referral&utm_campaign=Other%20Links>
Tél : +33 (0)5 62 24 47 62
118 Route d'Espagne, Bâtiment A, 3ème étage - 31100 TOULOUSE - FRANCE
www.valiantys.com
<http://www.valiantys.com?utm_source=Signature&utm_medium=referral&utm_campaign=Other%20Links>•
blog.valiantys.com
<http://blog.valiantys.com?utm_source=Signature&utm_medium=referral&utm_campaign=Other%20Links>
• twitter.com/Valiantys



*Consultez nos formations Atlassian
<http://www.valiantys.com/services/formation?utm_source=Signature%20Tagline&utm_medium=referral&utm_campaign=Other%20Links>
disponibles dans le monde entier et réservez vos places dès maintenant ! *Take
a look at our worldwide Atlassian training courses
<http://www.valiantys.com/en/our-services/training?utm_source=Signature%20Tagline&utm_medium=referral&utm_campaign=Other%20Links>
and book now!

<https://marketplace.atlassian.com/plugins/com.valiantys.spreadsheets>

**Comment by garysweaver** [comment]
Sébastien, sorry about that. I tested it at home with Confluence 5.9.2 on its own and it was fine, so released to marketplace. I would say that it is fine for it to be only compatible with 5.9.x and not 5.8.x or earlier.

Can you confirm that it is incompatible with Bob Swift CLI when using with Confluence 5.9.2 also? As I understood it, your PR was for 5.9 compatibility, so in marketplace I only set compatibility with 5.9.x.

Also, be sure to use the latest Atlassian SDK and ```atlas-mvn -Dmaven.test.skip=true clean install``` to build and test for 5.9.2. That is what the currently released version in marketplace was built with.

**Pull request merged**
